documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'

enhancement:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.py'
          - '.github/workflows/**'
          - 'config.json'
